//! Repo digest ("Kaşe"): a bounded, auto-generated summary of a project (directory tree, package scripts,
//! exported symbols per file, the head of docs/ARCHITECTURE-BRIEF.md) that every worker brief carries so a
//! model reads files only to edit or verify them instead of re-discovering the repository (2026-09-30: 530k
//! of 1.45M tokens in one run were file reads). Cached at `<root>/.silent/digest.md`, rebuilt when any
//! project file is newer than the cache.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

const SKIP_DIRS: &[&str] = &["node_modules", ".git", ".silent", "dist", "build", "target", ".next", ".venv", "venv", "__pycache__", ".cache", "coverage"];
const MAX_FILES: usize = 6000;

fn walk(dir: &Path, root: &Path, out: &mut Vec<(String, u64)>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    let mut items: Vec<_> = entries.flatten().collect();
    items.sort_by_key(|e| e.file_name());
    for entry in items {
        if out.len() >= MAX_FILES {
            return;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        let Ok(meta) = entry.metadata() else { continue };
        if meta.is_dir() {
            if SKIP_DIRS.contains(&name.as_str()) || (name.starts_with('.') && name != ".github") {
                continue;
            }
            walk(&entry.path(), root, out);
        } else if meta.is_file() && !name.starts_with('.') {
            if let Ok(rel) = entry.path().strip_prefix(root) {
                out.push((silent_runtime::paths::to_slash(rel), meta.len()));
            }
        }
    }
}

fn newest_mtime(dir: &Path) -> Option<std::time::SystemTime> {
    let mut files = Vec::new();
    walk(dir, dir, &mut files);
    files
        .iter()
        .filter_map(|(rel, _)| std::fs::metadata(dir.join(rel)).ok()?.modified().ok())
        .max()
}

/// Exported / public symbol names of one source file (cheap line regexes, no parser).
pub fn exports_of(path: &str, text: &str) -> Vec<String> {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    let mut out = Vec::new();
    for line in text.lines() {
        let l = line.trim_start();
        let name = match ext.as_str() {
            "ts" | "tsx" | "js" | "jsx" | "mjs" => l
                .strip_prefix("export ")
                .map(|r| r.trim_start_matches("default ").trim_start_matches("async ").trim_start_matches("declare "))
                .and_then(|r| {
                    for kw in ["function ", "const ", "class ", "interface ", "type ", "enum ", "let "] {
                        if let Some(rest) = r.strip_prefix(kw) {
                            return Some(rest);
                        }
                    }
                    None
                }),
            "rs" => l.strip_prefix("pub ").or_else(|| l.strip_prefix("pub(crate) ")).and_then(|r| {
                let r = r.trim_start_matches("async ");
                for kw in ["fn ", "struct ", "enum ", "trait ", "type ", "const ", "static "] {
                    if let Some(rest) = r.strip_prefix(kw) {
                        return Some(rest);
                    }
                }
                None
            }),
            "py" => l.strip_prefix("def ").or_else(|| l.strip_prefix("class ")),
            _ => None,
        };
        if let Some(rest) = name {
            let ident: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_').collect();
            if !ident.is_empty() && !out.contains(&ident) {
                out.push(ident);
            }
        }
    }
    out
}

fn is_source(rel: &str) -> bool {
    matches!(rel.rsplit('.').next().map(|e| e.to_ascii_lowercase()).as_deref(), Some("ts" | "tsx" | "js" | "jsx" | "mjs" | "rs" | "py"))
        && !rel.contains(".test.")
        && !rel.contains(".spec.")
        && !rel.starts_with("tests/")
}

/// Build the digest text for `root`, bounded to `max_bytes` (exports section is truncated first).
pub fn build_digest(root: &Path, max_bytes: usize) -> String {
    let mut files = Vec::new();
    walk(root, root, &mut files);
    let mut out = format!("# Repo digest (auto-generated by Silent, {} files; read a file only to edit or verify it)\n\n", files.len());
    // package.json scripts
    if let Ok(text) = std::fs::read_to_string(root.join("package.json")) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) {
            if let Some(scripts) = v.get("scripts").and_then(|s| s.as_object()) {
                out.push_str("## package.json scripts\n");
                for (k, val) in scripts {
                    out.push_str(&format!("- {k}: {}\n", val.as_str().unwrap_or("")));
                }
                out.push('\n');
            }
        }
    }
    // tree: one line per directory
    let mut dirs: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (rel, _) in &files {
        let (dir, name) = match rel.rsplit_once('/') {
            Some((d, n)) => (d.to_string(), n.to_string()),
            None => (".".to_string(), rel.clone()),
        };
        dirs.entry(dir).or_default().push(name);
    }
    out.push_str("## Tree (directory: files)\n");
    for (dir, names) in &dirs {
        let shown: Vec<&str> = names.iter().take(40).map(String::as_str).collect();
        let more = if names.len() > 40 { format!(" … +{}", names.len() - 40) } else { String::new() };
        out.push_str(&format!("- {dir}: {}{more}\n", shown.join(" ")));
    }
    out.push('\n');
    // architecture brief head
    if let Ok(text) = std::fs::read_to_string(root.join("docs/ARCHITECTURE-BRIEF.md")) {
        out.push_str("## docs/ARCHITECTURE-BRIEF.md (head)\n");
        for line in text.lines().take(60) {
            out.push_str(line);
            out.push('\n');
        }
        out.push('\n');
    }
    // exports (largest section, truncated to the budget)
    let mut exports = String::from("## Exports per file\n");
    for (rel, size) in &files {
        if !is_source(rel) || *size > 512 * 1024 {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(rel)) else { continue };
        let names = exports_of(rel, &text);
        if names.is_empty() {
            continue;
        }
        let shown: Vec<&str> = names.iter().take(30).map(String::as_str).collect();
        let more = if names.len() > 30 { format!(" … +{}", names.len() - 30) } else { String::new() };
        exports.push_str(&format!("- {rel}: {}{more}\n", shown.join(", ")));
    }
    let room = max_bytes.saturating_sub(out.len());
    if exports.len() > room {
        let mut cut = room.saturating_sub(24).min(exports.len());
        while cut > 0 && !exports.is_char_boundary(cut) {
            cut -= 1;
        }
        let head = &exports[..cut];
        let head = &head[..head.rfind('\n').unwrap_or(0)];
        out.push_str(head);
        out.push_str("\n… (exports truncated)\n");
    } else {
        out.push_str(&exports);
    }
    out
}

/// Digest of a reference repository (kit refs): a two-level tree plus the head of its README, so workers
/// read the digest instead of wandering through the clone.
pub fn build_ref_digest(dir: &Path, max_bytes: usize) -> String {
    let mut out = format!("# Reference digest: {} (auto-generated by Silent)\n\n## Tree (two levels)\n", dir.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default());
    let mut top: Vec<_> = std::fs::read_dir(dir).map(|r| r.flatten().collect()).unwrap_or_default();
    top.sort_by_key(|e| e.file_name());
    for e in top {
        let name = e.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || SKIP_DIRS.contains(&name.as_str()) {
            continue;
        }
        if e.path().is_dir() {
            let mut kids: Vec<String> = std::fs::read_dir(e.path()).map(|r| r.flatten().map(|k| k.file_name().to_string_lossy().into_owned()).filter(|n| !n.starts_with('.')).collect()).unwrap_or_default();
            kids.sort();
            let more = if kids.len() > 30 { format!(" … +{}", kids.len() - 30) } else { String::new() };
            kids.truncate(30);
            out.push_str(&format!("- {name}/: {}{more}\n", kids.join(" ")));
        } else {
            out.push_str(&format!("- {name}\n"));
        }
    }
    for readme in ["README.md", "readme.md", "README.rst", "README"] {
        if let Ok(text) = std::fs::read_to_string(dir.join(readme)) {
            out.push_str(&format!("\n## {readme} (head)\n"));
            for line in text.lines().take(60) {
                out.push_str(line);
                out.push('\n');
            }
            break;
        }
    }
    if out.len() > max_bytes {
        let mut cut = max_bytes;
        while cut > 0 && !out.is_char_boundary(cut) {
            cut -= 1;
        }
        out.truncate(cut);
        out.push_str("\n… (truncated)\n");
    }
    out
}

/// Write `SILENT-DIGEST.md` into a cloned reference repo if it is missing. Best effort.
pub fn ensure_ref_digest(dir: &Path) {
    let path = dir.join("SILENT-DIGEST.md");
    if path.exists() {
        return;
    }
    let _ = std::fs::write(&path, build_ref_digest(dir, 6 * 1024));
}

/// The project's digest text, from `<root>/.silent/digest.md` when it is newer than every project file,
/// else rebuilt (and cached). `max_bytes` defaults to 12 KB.
#[tauri::command]
pub fn repo_digest(root: String, max_bytes: Option<usize>) -> Result<String, String> {
    let root_path = PathBuf::from(&root);
    if !root_path.is_dir() {
        return Err(format!("{root} is not a directory"));
    }
    let budget = max_bytes.unwrap_or(12 * 1024).clamp(2 * 1024, 64 * 1024);
    let cache = root_path.join(".silent").join("digest.md");
    if let Ok(meta) = std::fs::metadata(&cache) {
        let fresh = match (meta.modified().ok(), newest_mtime(&root_path)) {
            (Some(cached), Some(newest)) => cached >= newest,
            _ => false,
        };
        if fresh {
            if let Ok(text) = std::fs::read_to_string(&cache) {
                if text.len() <= budget + 64 {
                    return Ok(text);
                }
            }
        }
    }
    let text = build_digest(&root_path, budget);
    if let Some(dir) = cache.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    let _ = std::fs::write(&cache, &text);
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture(tag: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!("silent-digest-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("src/game/player")).unwrap();
        std::fs::create_dir_all(root.join("node_modules/x")).unwrap();
        std::fs::create_dir_all(root.join("docs")).unwrap();
        std::fs::write(root.join("package.json"), r#"{"scripts":{"test":"vitest run","typecheck":"tsc --noEmit"}}"#).unwrap();
        std::fs::write(root.join("src/game/player/index.ts"), "export function createPlayer() {}\nexport const PLAYER_SPEED = 3\nexport interface PlayerState {}\nconst hidden = 1\nexport default class Foo {}\n").unwrap();
        std::fs::write(root.join("src/game/player/index.test.ts"), "export const t = 1\n").unwrap();
        std::fs::write(root.join("src/lib.rs"), "pub fn run() {}\npub struct Cfg;\nfn private() {}\n").unwrap();
        std::fs::write(root.join("node_modules/x/index.js"), "export const nope = 1\n").unwrap();
        std::fs::write(root.join("docs/ARCHITECTURE-BRIEF.md"), "# Brief\nline2\n").unwrap();
        root
    }

    #[test]
    fn exports_are_extracted_per_language() {
        assert_eq!(exports_of("a.ts", "export function f() {}\nexport const X = 1\nexport default class C {}\nexport type T = 1\nconst y = 2\n"), vec!["f", "X", "C", "T"]);
        assert_eq!(exports_of("a.rs", "pub fn run() {}\npub struct S;\nfn p() {}\npub(crate) fn q() {}\n"), vec!["run", "S", "q"]);
        assert_eq!(exports_of("a.py", "def go():\n    pass\nclass K:\n    pass\n"), vec!["go", "K"]);
    }

    #[test]
    fn digest_has_scripts_tree_brief_and_exports_and_skips_junk() {
        let root = fixture("build");
        let d = build_digest(&root, 12 * 1024);
        assert!(d.contains("- test: vitest run"), "{d}");
        assert!(d.contains("- src/game/player: index.test.ts index.ts"), "{d}");
        assert!(d.contains("# Brief"));
        assert!(d.contains("- src/game/player/index.ts: createPlayer, PLAYER_SPEED, PlayerState, Foo"), "{d}");
        assert!(d.contains("- src/lib.rs: run, Cfg"));
        assert!(!d.contains("index.test.ts:"), "tests are not listed under exports");
        assert!(!d.contains("node_modules"));
        let small = build_digest(&root, 2 * 1024);
        assert!(small.len() <= 2 * 1024 + 64, "{}", small.len());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn repo_digest_caches_and_rebuilds_when_files_change() {
        let root = fixture("cache");
        let first = repo_digest(root.to_string_lossy().into_owned(), None).unwrap();
        assert!(root.join(".silent/digest.md").is_file());
        std::thread::sleep(std::time::Duration::from_millis(1100));
        std::fs::write(root.join("src/game/player/extra.ts"), "export const LATE = 1\n").unwrap();
        let second = repo_digest(root.to_string_lossy().into_owned(), None).unwrap();
        assert!(second.contains("LATE"), "{second}");
        assert_ne!(first, second);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn reference_digest_lists_two_levels_and_readme_head() {
        let root = std::env::temp_dir().join(format!("silent-refdigest-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("src/engine")).unwrap();
        std::fs::write(root.join("README.md"), "# LittleJS\nTiny engine\n").unwrap();
        std::fs::write(root.join("src/engine/loop.js"), "").unwrap();
        ensure_ref_digest(&root);
        let d = std::fs::read_to_string(root.join("SILENT-DIGEST.md")).unwrap();
        assert!(d.contains("- src/: engine"));
        assert!(d.contains("# LittleJS"));
        let _ = std::fs::remove_dir_all(&root);
    }
}
